let suggestions = [
        "AZEITE",
        "AZEITE SACHE",
        "AÇUCAR SACHE",
        "ABACAXI",
        "ABACAXI CONGELADO",
        "ABOBORA",
        "ABOBRINHA",
        "ACEM",
        "AGRIAO",
        "ALCAPARRA",
        "ALECRIM",
        "ALFACE",
        "ALFACE AMERICANA",
        "ALFACE CRESPA",
        "ALFACE ROXA",
        "ALHO ",
        "ALHO DESIDRATADO",
        "ALHO EM PO",
        "ALHO FRITO",
        "ALHO PORO",
        "AMENDOA",
        "AMENDOIM CRU S-PELE S-SAL",
        "AMIDO DE MILHO",
        "AMORA CONGELADA",
        "ANIZ ESTRELADO",
        "ARROZ BRANCO",
        "ARROZ PARBOLIZADO",
        "AVE TEMPERADA",
        "AZEITONA PRETA",
        "AZEITONA PRETA S-C",
        "AZEITONA VERDE",
        "AZEITONA VERDE S-C",
        "AÇAFRÃO",
        "AÇUCAR MASCAVO",
        "AÇUCAR REFINADO",
        "BACALHAU DESFIADO",
        "BACALHAU LOMBO",
        "BACALHAU POSTA",
        "BACON",
        "BACON FATIADO",
        "BAGUETE",
        "BANANA",
        "BANANA CHIPS",
        "BARRA CHOCOLATE 90G",
        "BARRIGA SUINA",
        "BATATA ASTERIX",
        "BATATA BOLINHA",
        "BATATA DOCE",
        "BATATA FRITA",
        "BATATA INGLESA",
        "BATATA PALHA",
        "BERINJELA",
        "BETERRABA",
        "BICARBONATO DE SODIO",
        "BIG CHICKEN NUGGTES",
        "BISTECA SUINA",
        "BOLINHO DE BACALHAU",
        "BOLINHO DE MANDIOCA",
        "BROCOLIS",
        "BROTO",
        "CAFÉ EM PÓ ",
        "CAJU",
        "CALABRESA CURADA",
        "CALABRESA FRESCA",
        "CALDO CARNE",
        "CALDO DE OSSOBUCO",
        "CALDO GALINHA",
        "CALDO LEGUMES",
        "CAMARAO",
        "CANELA CASCA",
        "CANELA PO",
        "CAPELLETI ",
        "CARNE CURADA DESF",
        "CARNE MOIDA",
        "CARNE MOIDA REFOGADA",
        "CARNE SECA ",
        "CARNE SECA DESFIADA",
        "CARNE SECA TRASEIRO",
        "CASTANHA DE CAJU",
        "CATUPIRY ",
        "CEBOLA",
        "CEBOLA CRISPY",
        "CEBOLA EM PO",
        "CEBOLA P-CONSERVA",
        "CEBOLA ROXA",
        "CEBOLINHA",
        "CENOURA",
        "CENOURA RALADA",
        "CEREJA CALDA",
        "CHAMPIGNON FATIADO",
        "CHEDDAR FATIADO",
        "CHEIRO VERDE",
        "CHIMICHURRI ",
        "CHOCOLATE EM PO",
        "CHUCRUTE TEMPERADO",
        "COCO RALADO",
        "COCO SECO",
        "COCO VERDE DESCASCADO",
        "COENTRO",
        "COGUMELO SHITAKE",
        "COLORAU",
        "COMINHO",
        "CONTRA FILE",
        "COPA FATIADA",
        "CORANTE LIQUIDO",
        "CORAÇAO ALCATRA",
        "CORAÇAO FRANGO",
        "COSTELA",
        "COSTELA DO TRASEIRO",
        "COSTELA RECHEADA",
        "COSTELA SUINA",
        "COSTELAS GRANDES",
        "COSTELAS MEDIAS",
        "COSTELAS PEQUENAS",
        "COSTELINHA",
        "COUVE",
        "COUVE FLOR",
        "COXA FRANGO",
        "COXA RECHEADA",
        "COXA SOBRECOXA",
        "COXAO MOLE",
        "COXINHA ASA FRANGO",
        "COXINHA COM CATUPIRY",
        "COXINHAS DOCES",
        "CRAVO DA INDIA",
        "CREAM CHEESE",
        "CREME CULINARIO",
        "CREME DE LEITE",
        "CREME DE LEITE SEM LACTOSE",
        "CREME DE RICOTA",
        "EMULSIFICANTE SORVETE",
        "ERVILHA CONGELADA",
        "ERVILHA CONSERVA",
        "EXTRATO TOMATE",
        "FARINHA FIOCCO",
        "FARINHA ESPECIAL",
        "FARINHA FLOCADA",
        "FARINHA MANDIOCA",
        "FARINHA MILHO",
        "FARINHA PANKO",
        "FARINHA ROSCA",
        "FARINHA TORRADA",
        "FARINHA TRIGO",
        "FEIJAO CARIOCA",
        "FEIJAO FRADINHO",
        "FERMENTO EM PO",
        "FILE DE PEITO FRANGO",
        "FILE DE PERNIL",
        "FILE DE TILAPIA", 
        "FILE MIGNON BOV",
        "FILE MIGNON SUI",
        "FLOCAO DE MILHO",
        "FRAMBOESA CONGELADA",
        "FRISCO",
        "FRUTAS AMARELA CONG",
        "FRUTAS DESIDRATADAS",
        "FRUTAS VERMELHAS",
        "FRUTAS VERMELHAS CONGELADO",
        "FUBÁ",
        "GELEIA",
        "GELEIA FRUTAS VERMELHAS",
        "GELEIA PIMENTA",
        "GENGIBRE",
        "GLUCOSE DE MILHO",
        "GORDURA VEGETAL",
        "HORTELA",
        "IOGURTE FRUTA",
        "IOGURTE NATURAL",
        "JERKED BEEF ",
        "JOELHO SUINO",
        "KIWI",
        "LARANJA BAHIA",
        "LARANJA LIMA",
        "LARANJA PERA",
        "LEGUMES CONGELADA",
        "LEGUMES EM PO",
        "LEITE CONDENSADO 395G",
        "LEITE DE COCO",
        "LEITE INTEGRAL",
        "LEITÃO A PASSARINHO",
        "LEMON PEPPER",
        "LIMAO",
        "LIMAO CRAVO",
        "LIMAO DESIDRATADO",
        "LIMAO SICILIANO",
        "LIMAO TAITI",
        "LINGUA ",
        "LINGUIÇA APIMENTADA",
        "LINGUIÇA CALABRESA",
        "LINGUIÇA CALABRESA DEFUMADA",
        "LINGUIÇA FRESCAL GROSSA",
        "LINGUIÇA PAIO",
        "LINGUIÇA PERNIL C-ALHO",
        "LINGUIÇA PROVOLONE",
        "LINGUIÇA SUINA",
        "LINGUIÇA TOSCANA",
        "LOMBO SUINO",
        "LOURO",
        "MACARRAO ESPAGUETE",
        "MACARRAO PARAFUSO C-OVOS",
        "MADIOCA PALITO CONG",
        "MAIONESE",
        "MAIONESE SACHE",
        "MANDIOCA",
        "MANJERICAO",
        "MANTEIGA",
        "MANTEIGA DE GARRAFA",
        "MARACUJA",
        "MARACUJA POLPA",
        "MARACUJA S-SEMENTE CONGELADA",
        "MASSA FOLHADA ROLO",
        "MASSA LASANHA SEMOLA",
        "MASSA PASTEL",
        "MASSA PASTEL ROLO",
        "MAÇA",
        "MAÇA DESIDRATADA",
        "MAÇA TINGIDA",
        "MEIO ASA FRANGO",
        "MEL",
        "MELANCIA",
        "MILHO VERDE CONSERVA",
        "MINI CHICKEN QUEIJO CONGELADO",
        "MIRTILO CONGELADO",
        "MIX PIMENTA GRÃOS",
        "MIX PIMENTOES FATIADOS",
        "MOELA CONGELADA",
        "MOLHO TABASCO ORIGINAL",
        "MOLHO TABASCO SUAVE",
        "MOLHO TOMATE",
        "MOLHO DEFUMADO",
        "MOLHO DRENADO",
        "MOLHO INGLÊS",
        "MOLHO LACTEO CHEDDAR ",
        "MOLHO MOSTARDA",
        "MOLHO MOSTARDA SACHE",
        "MOLHO PIMENTA",
        "MOLHO PIMENTA SACHE",
        "MOLHO SHOYO",
        "MORANGO",
        "MORANGO CONGELADO",
        "MORTADELA",
        "MUSCULO",
        "NOZ MOSCADA MOIDA",
        "OLEO ALGODAO ELOGIATA",
        "OLEO COMPOSTO",
        "OLEO LUBRIFICANTE",
        "OLEO PEROBA",
        "OLEO VEGETAL",
        "OREGANO",
        "ORELHA",
        "OSSO BUCO",
        "OVO DE CODORNA",
        "OVOS",
        "PALETA",
        "PALMITO AÇAI",
        "PALMITO JUÇARA",
        "PALMITO PUPUNHA",
        "PALMITO REAL",
        "PANCETA",
        "PAO DE QUEIJO",
        "PAO FORMA ARTESANO",
        "PAO FRANCES",
        "PAO HOT DOG",
        "PAPRICA",
        "PATINHO",
        "PE",
        "PEITO DE FRANGO",
        "PEPINO ",
        "PEPINO CONSERVA",
        "PEPPERONI FATIADO",
        "PERA PORTUGUESA",
        "PERNIL",
        "PESSEGO",
        "PICANHA",
        "PICLES", 
        "PIMENTA BIQUINHO",
        "PIMENTA CALABRESA",
        "PIMENTA DEDO DE MOÇA",
        "PIMENTA DEFUMADA C-BACON",
        "PIMENTA DO REINO",
        "PIMENTAO AMARELO",
        "PIMENTAO VERDE",
        "PIMENTAO VERMELHO",
        "PITAYA",
        "PONTA ALCATRA",
        "PRESUNTO",
        "QUEIJO AZUL",
        "QUEIJO BRIE",
        "QUEIJO BURRATA BUFALA",
        "QUEIJO CHEDDAR",
        "QUEIJO COALHO",
        "QUEIJO GORGONZOLA",
        "QUEIJO MINAS BURITIS",
        "QUEIJO MUSSARELA",
        "QUEIJO MUSSARELA RALADO",
        "QUEIJO PARMESAO",
        "QUEIJO PRATO",
        "QUEIJO PROVOLONE",
        "QUEIJO RALADO PARMESAO",
        "QUEIJO RICOTA",
        "QUIABO",
        "RABO",
        "REFRESCO EM PO AMAVITA 1KG",
        "REFRESCO EM PO BRASSUKK 20G",
        "REFRESCO EM PO FRISCO",
        "REFRESCO EM PO PROMIX 250G",
        "REFRESCO EM PO QUALIMAX 15G",
        "REFRESCO EM PO QUALIMAX 1KG",
        "REPOLHO",
        "REPOLHO ROXO",
        "REQUEIJAO",
        "REQUEIJAO CHEDDAR ",
        "RUCULA",
        "SAL CHURRASCO",
        "SAL GROSSO",
        "SAL REFINADO",
        "SAL SACHE",
        "SALAME ITALIANO FATIADO",
        "SALSA",
        "SALSAO",
        "SALSICHA",
        "SALSICHA BRANCA WEISSWURST G",
        "SALSICHA CERVELA G",
        "SALSINHA",
        "SUINO MOIDO",
        "TOMATE CEREJA ",
        "TOMATE ITALIANO",
        "TOMATE MOLHO",
        "TOMATE SALADA",
        "TOMILHO",
        "TORRADA INTEGRAL",
        "TOUCINHO",
        "TULIPA FRANGO",
        "UVA ITALIA",
        "UVA PASSA",
        "UVA ROXA",
        "UVA VERDE",
        "VAGEM",
        "VINAGRE ALCOOL BRANCO 750ML",
        "VINAGRE ALCOOL COLORIDO 750ML",
        "VINAGRE ALCOOL MAÇA 750ML",
        "VINAGRE BALSAMICO",
        "VINAGRE VINHO TINTO 750ML",
        "APPLE DREAM",
        "PETIT GATEAU",
        "SURPRISE",
        "TORTA ALEMÃ",
        "TORTA ALMENDRADA",
        "TORTA BOMBOM AVELA",
        "TORTA BOMBOM BRIGADEIRO",
        "TORTA BOMBOM TROPICAL",
        "TORTA DE MAÇÃ",
        "TORTA HOLANDESA",
        "BISCOITO LOOK 55G",
        "BISCOITO MINI OREO 35G",
        "BISCOITO NESFIT",
        "BISCOITO WAFER BIS 126G",
        "BOLO DE COCO",
        "BOMBOM",
        "BROA DE FUBA",
        "COPINHO GELATO",
        "FERRERO ROCHER T3",
        "FINI BANANAS",
        "FINI DENTADURA",
        "FINI MINHOCA CITRICA",
        "GELATO BRIGADEIRO DO TIO GU",
        "GELATO CHOCOLATE BELGA",
        "GELATO CREME",
        "GELATO MIONINHO",
        "GELATO MORANGO ZERO LACTOSE",
        "HALLS 84G",
        "KINDER TRONKY",
        "KIT KAT BRANCO 41,5G",
        "KIT KAT DARK 41,5G",
        "NUTELLA 140G",
        "NUTELLA B-READY",
        "OVO CHOCOLATE",
        "PASTILHA FINI",
        "PIRAQUE ROLADINHO 40X75G",
        "PUDIM DE LEITE CONDENSADO PEQ",
        "SORVETE JUNDIA CREME  2L",
        "SORVETE KIBON CREME 1,5L",
        "SORVETE LAKA 1,5L",
        "SORVETE NESTLE CREME 1,5L",
        "SORVETE NESTLE GALAK 1,5L",
        "SORVETE QA CREME",
        "TIC TAC LARANJA 14G",
        "TIC TAC MENTA 14G",
        "TIC TAC MORANGO 14G",
        "TRIDENT HORTELA 8G",
        "TRIDENT MENTA 8G",
        "CIGARRO DUNHILL CARLTON",
        "CIGARRO DUNHILL RED BOX",
        "CIGARRO MARLBORO BLUE ICE MENT",
        "CIGARRO MARLBORO BOX",
        "CIGARRO MARLBORO DOUBLE FUSION",
        "CIGARRO MARLBORO DOUBLE MIX",
        "CIGARRO MARLBORO FILTER PLUS",
        "CIGARRO MARLBORO LI BOX",
        "CIGARRO MARLBORO TROPICAL FUSION",

]